<?php
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Add the settings page to the admin menu.
 */
function mcp_add_settings_menu() {
    add_submenu_page(
        'course_builder_page',
        __( 'Settings', 'med-course-plugin' ),
        __( 'تنظیمات وابستگی‌ها', 'med-course-plugin' ),
        'manage_options',
        'mcp-settings',
        'mcp_render_settings_page'
    );
}
add_action( 'admin_menu', 'mcp_add_settings_menu' );

/**
 * Render the settings page.
 */
function mcp_render_settings_page() {
    if ( isset( $_POST['mcp_settings_submit'] ) && check_admin_referer( 'mcp_settings_action', 'mcp_settings_nonce' ) ) {
        $local_enabled = isset( $_POST['mcp_local_assets'] ) ? '1' : '0';
        update_option( 'mcp_local_assets', $local_enabled );

        if ( ! empty( $_FILES['mcp_dependency_zip']['tmp_name'] ) ) {
            mcp_handle_dependency_upload( $_FILES['mcp_dependency_zip'] );
        }

        echo '<div class="notice notice-success is-dismissible"><p>' . __( 'Settings saved.', 'med-course-plugin' ) . '</p></div>';
    }

    $local_enabled = get_option( 'mcp_local_assets', '0' );
    $vendor_path = plugin_dir_path( dirname( __FILE__ ) ) . 'assets/vendor/';
    $fa_exists = file_exists( $vendor_path . 'fontawesome/css/all.min.css' );
    $s2_exists = file_exists( $vendor_path . 'select2/css/select2.min.css' );
    ?>
    <div class="wrap">
        <h1><?php _e( 'Dependency Settings', 'med-course-plugin' ); ?></h1>
        <form method="post" enctype="multipart/form-data">
            <?php wp_nonce_field( 'mcp_settings_action', 'mcp_settings_nonce' ); ?>
            <table class="form-table">
                <tr>
                    <th scope="row"><?php _e( 'Local Assets Mode', 'med-course-plugin' ); ?></th>
                    <td>
                        <label>
                            <input type="checkbox" name="mcp_local_assets" value="1" <?php checked( $local_enabled, '1' ); ?>>
                            <?php _e( 'Use local assets instead of CDN', 'med-course-plugin' ); ?>
                        </label>
                        <p class="description"><?php _e( 'If enabled, the plugin will attempt to load Font Awesome and Select2 from the local vendor directory.', 'med-course-plugin' ); ?></p>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?php _e( 'Status', 'med-course-plugin' ); ?></th>
                    <td>
                        <ul>
                            <li>Font Awesome: <?php echo $fa_exists ? '<span style="color:green;">✓ Found</span>' : '<span style="color:red;">✗ Not Found</span>'; ?></li>
                            <li>Select2: <?php echo $s2_exists ? '<span style="color:green;">✓ Found</span>' : '<span style="color:red;">✗ Not Found</span>'; ?></li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?php _e( 'Upload Dependencies ZIP', 'med-course-plugin' ); ?></th>
                    <td>
                        <input type="file" name="mcp_dependency_zip" accept=".zip">
                        <p class="description">
                            <?php _e( 'Upload the ZIP file generated by the downloader tool.', 'med-course-plugin' ); ?>
                            <br>
                            <a href="<?php echo plugin_dir_url( dirname( __FILE__ ) ) . 'tools/downloader.html'; ?>" target="_blank"><?php _e( 'Open Downloader Tool', 'med-course-plugin' ); ?></a>
                        </p>
                    </td>
                </tr>
            </table>
            <p class="submit">
                <input type="submit" name="mcp_settings_submit" class="button button-primary" value="<?php _e( 'Save Settings', 'med-course-plugin' ); ?>">
            </p>
        </form>
    </div>
    <?php
}

/**
 * Handle dependency ZIP upload and extraction.
 */
function mcp_handle_dependency_upload( $file ) {
    require_once ABSPATH . 'wp-admin/includes/file.php';
    WP_Filesystem();
    global $wp_filesystem;

    $vendor_path = plugin_dir_path( dirname( __FILE__ ) ) . 'assets/vendor/';

    if ( ! file_exists( $vendor_path ) ) {
        wp_mkdir_p( $vendor_path );
    }

    $unzipfile = unzip_file( $file['tmp_name'], $vendor_path );

    if ( is_wp_error( $unzipfile ) ) {
        wp_die( $unzipfile->get_error_message() );
    }
}
